name: Audit

on:
  pull_request:
    branches:
      - master
      - zowe-v?-lts
      - next
  schedule:
    - cron: '0 10 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Use Node.js LTS
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: lts/*

    - name: Check Vulnerabilities
      run: npm audit --production --audit-level=moderate
