name: Audit

on:
  pull_request:
    branches:
      - master
      - zowe-v1-lts
      - next
  # schedule:
  #   - cron: '0 10 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Check Vulnerabilities
      run: npm audit --production --audit-level=moderate
